### ISSUE TITLE
The package is not listed by the Package Control

### ISSUE THREAD

**Issue by sigod** [aidenfoxivey/sublime-zig-unofficial#5]
This package isn't listed by the Install Package command in Sublime Text. This seems to be due to its "missing" status on the Package Control site:
> Package info was unavailable last time crawler ran. No valid semver tags found at https://github.com/aidenfoxivey/sublime-zig-unofficial/tags for the package "ZigUnofficial" in the repository /var/www/packagecontrol.io/channel/repository.json.

**Comment by aidenfoxivey** [comment]
@sigod Sorry! I missed this earlier. 🤦🏻 

I've just added a release.

**Comment by aidenfoxivey** [comment]
![CleanShot 2024-10-21 at 22 52 28@2x](https://github.com/user-attachments/assets/1cfc31f3-724c-4f14-babf-8f6fe1c5751c)
And we're back!

**Comment by aidenfoxivey** [comment]
Turns out it was due to a faulty forgejo configuration that was overwriting all my commits.
